on: push
name: Draft Release
jobs:
  draftRelease:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Draft Release
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm run check-types
